name: "Mirror .github"

on:
  push: 
    branches:
      - "main"
      - "dev"

jobs:
  mirror:
    uses: org013/.github/workflows/mirrors.yml@main
    secrets: 
      CODEBERG_USERNAME: ${{ secrets.CODEBERG_USERNAME }}
      CODEBERG_TOKEN: ${{ secrets.CODEBERG_TOKEN }}
    with:
      codeberg-repo: https://codeberg.org/Guz013/.codeberg
